# API Keys, sensitive data, credentials
# GitLeaks
name: Secrets Scan

on:
    workflow_calls:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Run GitLeaks Scanner
              uses: gitleaks/gitleaks-actions@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
